[package]
name = "watchdog"
version = "0.2.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
csv = "1.3.1"
serde = { version = "1.0.215", features = ["derive"] }
sysinfo = "0.33.0"
toml = "0.8.19"
